### ISSUE TITLE
Big Sur reboot loop (at installation)

### ISSUE THREAD

**Issue by freber** [SchmockLord/Hackintosh-Intel-i9-10900k-AsRock-Z490-Phantom-ITX-TB3#10]
To begin with, big thank you for this extensive work and documentation. It's really inspiring and valuable for someone coming into this world. 

I've built a system based on this MB with the only difference that I don't use any dedicated GPU. I've removed all external GPU add-ons from your configuration but still got the same issues. I'm trying to install Big Sur and after the first reboot I end up in a reboot loop with very short cycles. There is no other output to guide me, the Apple logo shows up and then a reboot.

Any advice would be very valuable.

**Comment by SchmockLord** [comment]
Hi @freber 

thanks. Check your BIOS settings again. Especially Secure Boot, CFG Unlock and CSM need to be disabled.

And regarding the config, disable the SSDT-5700XT.aml and the DAGPM.kext. Also remove the agdpmod=pikera in the boot args.

**Comment by freber** [comment]
Thanks for the advice. Sorted it out eventually by setting **SecureBootMode=Disabled**

This solved the problem caused by

```
32:848 00:028 AAPL: #[EB.SB.VK|!] Err(0xE) <- EB.LD.LF
32:878 00:029 AAPL: #[EB.LD.LKCFFP|!] Err(0x1A) <- EB.SB.SBVK
33:566 00:688 AAPL: #[EB|CS:SRBM] secure-boot
33:595 00:029 AAPL: #[EB|FWFM] 0x00000000FFDFFF7F
33:625 00:029 AAPL: #[EB|FWFT] 0x00000000FD8FF576
33:656 00:031 AAPL: #[EB|B:RB]
33:685 00:029 AAPL: #[EB|WL] 0 0 0x01 0x41  24 0x0E
33:720 00:034 AAPL: #[EB|REBOOT] 1
33:750 00:029 AAPL: #[EB|LOG:RESET:RECOVERY] 2020-10-09T15:53:56
```

**Comment by malibio** [comment]
I know this has been closed, but I wanted to quickly comment and ask a follow up question:

I have agdpmod=pikera in my boot-args, but everything still works fine. Even my TB3 display output works!

What does this argument do?

> Hi @freber
> 
> thanks. Check your BIOS settings again. Especially Secure Boot, CFG Unlock and CSM need to be disabled.
> 
> And regarding the config, disable the SSDT-5700XT.aml and the DAGPM.kext. Also remove the agdpmod=pikera in the boot args.
