### ISSUE TITLE
Sidecar Problems

### ISSUE THREAD

**Issue by RaginBajin** [SchmockLord/Hackintosh-Intel-i9-10900k-AsRock-Z490-Phantom-ITX-TB3#11]
Wondering what programs you tested to validate that sidecar was successfully working. I’ve mimicked the entire build you have other than OC’ing it and having a hard time getting it to work.  I’m wondering to test it against the same programs you used to know if its working or not.  I was using FCPX and just getting a black screen. Tried all the tricks, etc. Running iMac20,2.

**Comment by SchmockLord** [comment]
It mainly depends on your iGPU settings in the BIOS. You need to set IGPU-Multi Monitor to enabled. This forces the iGPU to be enabled, even when a discrete graphics card is detected.

It just works for me. Enable it and I see my Desktop extended on the iPad. Used it with Capture One.

**Comment by malibio** [comment]
I can also verify that Sidecar works...I have an iPad Pro that I can use as a secondary display.

![image](https://user-images.githubusercontent.com/3272436/95733672-c082a000-0c82-11eb-8426-80a7ca7178cd.png)

**Comment by RaginBajin** [comment]
You are right! I doubled checked the BIOS version last night and noticed that I wasn't using the same one you were.  That caused me to update as well as go through and validate the iGPU settings.  That got sidecar working as it should.

Now, though, it seems to have caused me a different issue where Final Cut Pro will not start up and immediately crashes and it seems to all relate to the use of the iGPU. :( 

Any ideas on that..

**Comment by RaginBajin** [comment]
I'm wondering if I have to change the config.plist  to 0300C89B for AAPL,ig-platform-id. https://dortania.github.io/OpenCore-Install-Guide/config.plist/comet-lake.html#deviceproperties 

What do you think?

**Comment by fidalgodev** [comment]
> I'm wondering if I have to change the config.plist to 0300C89B for AAPL,ig-platform-id. https://dortania.github.io/OpenCore-Install-Guide/config.plist/comet-lake.html#deviceproperties
> 
> What do you think?

Config Mac20,2 already has that at least. The iGPU is used for computing only already with `0300C89B`

**Comment by SchmockLord** [comment]
I can use sidecar with iMac20,2 and iGPU setup for computing only 0300C89B.

often it simply works. But sometimes I also get a timeout when I try to connect to my iPad. I guess this has nothing to do with Hackintosh in general.

**Comment by RaginBajin** [comment]
So, sidecar is good to go. I have fixed that.. 

It does look like the config.plist that I am using from your repo which was the iMac20,2 looks to not be using the 0300C89B. 

![image](https://user-images.githubusercontent.com/801660/95878816-794fea00-0d2a-11eb-94d3-4d9277a23d5b.png)

**Comment by RaginBajin** [comment]
Yep that fixed it... Setting that value to 0300C89B gives me Sidecar as well as Final Cut Pro working.
