### ISSUE TITLE
Use  NVMeFix.kext to fix power and energy consumption on these drives

### ISSUE THREAD

**Issue by fidalgodev** [SchmockLord/Hackintosh-Intel-i9-10900k-AsRock-Z490-Phantom-ITX-TB3#15]
As an improvement, since you use an NVMe (like me), it is recommended to use NVMeFix.kext.

https://dortania.github.io/Anti-Hackintosh-Buyers-Guide/Storage.html

**Comment by tristan-k** [comment]
Isn't this only needed for Samsung NVMe SSDs?

**Comment by fidalgodev** [comment]
> Isn't this only need for Samsung NVMe SSDs?

From the link I just posted:

> For all NVMe SSDs, its recommended to use NVMeFix.kext to fix power and energy consumption on these drives.

**Comment by tristan-k** [comment]
Thanks. I've overlooked that. I thought it was an issue bound to the samsung nvme controllers.

**Comment by fidalgodev** [comment]
I'm using this and my nvme ssd temps dropped to because this fix power usage. Up to you if you want to include in next release.
