### ISSUE TITLE
no automatic login

### ISSUE THREAD

**Issue by phi-alek** [SchmockLord/Hackintosh-Intel-i9-10900k-AsRock-Z490-Phantom-ITX-TB3#16]
I can't login automatically. If i disable automatic user login, i have a black screen when mac os catalina boots up. I need to write my password to enable the graphics. Then i can login and have enter my password again.
With enabled automatic login, i also need to enter my password after boot up or when i want to exit the screensafer, which is very odd.

i have an rx5500xt so i have changed the SSDT-RX 5500 XT-Version 1.0 file and deleted the rx5700xt. in the config file i have changed that as well. i have also added the intel bluetooth and wifi kexts which work great.

does anybody know why my login behaves like this? thank you!

**Comment by fidalgodev** [comment]
Working fine here

**Comment by phi-alek** [comment]
Automatic login works now.
