### ISSUE TITLE
No Audio via DisplayPort (iGPU)

### ISSUE THREAD

**Issue by malibio** [SchmockLord/Hackintosh-Intel-i9-10900k-AsRock-Z490-Phantom-ITX-TB3#18]
Has anyone gotten the audio via the iGPU (DisplayPort) to work? I've got built-in speakers in my monitor (display works), but no sounds come out :-(

**Comment by yuandalu** [comment]
> Has anyone gotten the audio via the iGPU (DisplayPort) to work? I've got built-in speakers in my monitor (display works), but no sounds come out :-(

Turn off the monitor and turn it on again

**Comment by SchmockLord** [comment]
Should be fixed now. Can you please test it?
