### ISSUE TITLE
Sapphire Nitro+ RX 5700 XT 8G GDDR6

### ISSUE THREAD

**Issue by astralrick** [SchmockLord/Hackintosh-Intel-i9-10900k-AsRock-Z490-Phantom-ITX-TB3#20]
I have Sapphire Nitro+ RX 5700 XT 8G GDDR6 which is different than your Sapphire Pulse 5700 XT. Would I be okay to use your SSDT-RX5700XT.aml or i need to use another one?

**Comment by SchmockLord** [comment]
Yes. You can use it without any adjustments.

**Comment by astralrick** [comment]
Thanks
