### ISSUE TITLE
Black screen crashes

### ISSUE THREAD

**Issue by fidalgodev** [SchmockLord/Hackintosh-Intel-i9-10900k-AsRock-Z490-Phantom-ITX-TB3#24]
Hello

Using the exact same GPU/Mobo/CPU and Ram.
Using latest EFI just changed Serials on config file..

I keep getting random crashes where my both screen goes black and the PC crashes.
But when booting up again I don't get that Error display screen, so doesn't look like a Kernel Panic.

Looks like a GPU related thing? Never had this happening before on Version 1... Only 2 and 3 releases.

Bios settings are the same as yours

**Comment by fidalgodev** [comment]
Are you using iMac or Mac Pro config? Starting to think this might be related to the iGPU acceleration

**Comment by fidalgodev** [comment]
Changed my config (updated serials also) for the iMacPro1,1. Disabled iGPU in BIOS.

Let's see if this keeps happening

**Comment by SchmockLord** [comment]
I use the iMac20,2 config. No issues. Do you have overclocking applied?

**Comment by fidalgodev** [comment]
No I do not, only XMP of the memory. I run cinebench over and over without issues, I don't think it's CPU related... The screens just go black, I still hear audio for some secs and then it crashes. I think this has to be GPU related

**Comment by fidalgodev** [comment]
Im clueless on why this happens tho, it's totally random. Exact same Hardware. So it can only be either BIOS settings or Catalina/Big Sur differences? Since you use Big Sur and I use Catalina.

Would the Tier 2 patreon give me some support from you? Maybe updated BIOS settings (there are some settings missing like RAM settings and AI Tweaker page). 

I would really like to fix this issue...

**Comment by fidalgodev** [comment]
Just wondering, could this black screen crashes be related with this being removed from the config?

```
<dict>
			<key>PciRoot(0x0)/Pci(0x2,0x0)</key>
			<dict>
				<key>AAPL,ig-platform-id</key>
				<data>BwCbPg==</data>
				<key>device-id</key>
				<data>mz4AAA==</data>
				<key>framebuffer-con0-busid</key>
				<data>AgAAAA==</data>
				<key>framebuffer-con0-enable</key>
				<data>AQAAAA==</data>
				<key>framebuffer-con0-flags</key>
				<data>xwMAAA==</data>
				<key>framebuffer-con0-index</key>
				<data>AgAAAA==</data>
				<key>framebuffer-con0-pipe</key>
				<data>CgAAAA==</data>
				<key>framebuffer-con0-type</key>
				<data>AAgAAA==</data>
				<key>framebuffer-con1-busid</key>
				<data>BAAAAA==</data>
				<key>framebuffer-con1-enable</key>
				<data>AQAAAA==</data>
				<key>framebuffer-con1-flags</key>
				<data>xwMAAA==</data>
				<key>framebuffer-con1-index</key>
				<data>AwAAAA==</data>
				<key>framebuffer-con1-pipe</key>
				<data>CAAAAA==</data>
				<key>framebuffer-con1-type</key>
				<data>AAgAAA==</data>
				<key>framebuffer-con2-busid</key>
				<data>AQAAAA==</data>
				<key>framebuffer-con2-enable</key>
				<data>AQAAAA==</data>
				<key>framebuffer-con2-flags</key>
				<data>xwMAAA==</data>
				<key>framebuffer-con2-index</key>
				<data>AQAAAA==</data>
				<key>framebuffer-con2-pipe</key>
				<data>CQAAAA==</data>
				<key>framebuffer-con2-type</key>
				<data>AAQAAA==</data>
				<key>framebuffer-fbmem</key>
				<data>AACQAA==</data>
				<key>framebuffer-patch-enable</key>
				<data>AQAAAA==</data>
				<key>framebuffer-stolenmem</key>
				<data>AAAwAQ==</data>
			</dict>
```

Before we would set the `framebuffer-stolenmem` in the config, I'm not sure what value it was?
But according to [this](https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md#intel-uhd-graphics-610-655-coffee-lake-and-comet-lake-processors), our Hd630 has a stolen memory of 58MB (not 64MB).

Now that this settings are not on the config, and we set it manually in the BIOS to 64MB, can that be the root of the issue?

**Comment by fidalgodev** [comment]
Updated to bios 1.40A beta and didn't had this crash, it's been 5 days already. Wondering if that was the issue?

It was the only thing I changed

**Comment by fidalgodev** [comment]
Never mind it happened again today... Im clueless on what it could be. I'm inclined to GPU/iGPU related because when it happens, i seem to have twitch opened, so maybe it has to do with Video acceleration of some sort
