### ISSUE TITLE
What is the Disable CNVW SSDT?

### ISSUE THREAD

**Issue by fidalgodev** [SchmockLord/Hackintosh-Intel-i9-10900k-AsRock-Z490-Phantom-ITX-TB3#27]
I can't find anything online about this one. I think it disables the CNVI card, but since we replaced the Intel card with a Custom one, we are still using the mini pcie slot of it? Why disable it?

I assume the SSDT-TB3HP.aml is done after following [this](https://github.com/osy86/ThunderboltReset) Guide?

Just trying to dig deeper and understand what each thing is doing :D 

Also wondering, do we need SSDT-USBW.aml and USBWakeFixup.kext?
According to the [guide](https://dortania.github.io/OpenCore-Post-Install/usb/misc/keyboard.html#method-1-add-wake-type-property-recommended), we should only need 1 of the methods, and we already use method 1: `acpi-wake-type | Data | <01>`

**Comment by fidalgodev** [comment]
Acording do the creator of this SSDT, this is not needed and does not work.

> Also I saw some people with this board on github using SSDT-Disable-CNVW.aml, but after some search I can't figure out what this SSDT is doing?

> I created that SSDT originally for Z390 Designare, but it does not work in Z490 Vision D. Fortunately there's no need for it on this system. Its purpose is to hide the Intel CNVi WiFi module from macOS.

**Comment by fidalgodev** [comment]
Also with the new Whatever Green, there is no need to fake iGPU of the 10900K :)

> With new WhateverGreen Kext is it still necessary to fake the device-id of the iGPU of a 10900K to C59B0000?

> Fortunately we no longer need to fake the iGPU device ID! The last couple of OpenCore EFI zips in this thread discontinued the Fake_PCIID for Intel iGPU/HDMI-Audio.

**Comment by klich3** [comment]
Is a Intel Wifi module normally is on _sb.pc00
