### ISSUE TITLE
Temperature Sensors not Working

### ISSUE THREAD

**Issue by fidalgodev** [SchmockLord/Hackintosh-Intel-i9-10900k-AsRock-Z490-Phantom-ITX-TB3#3]
When doing: `sudo powermetrics`

I get:

```
**** SMC sensors ****

Invalid key detected!
Invalid key detected!
Invalid key detected!
Invalid key detected!
Invalid key detected!
Invalid key detected!
Invalid key detected!
Invalid key detected!
Invalid key detected!
```

I don't think the power sensors are working correctly

**Comment by SchmockLord** [comment]
Yeah I have noticed that too. But I don't really know how to fix that. I think it is simply that the AsRocks Motherboard sensors are not supported by VirtualSMC.
