### ISSUE TITLE
Can thunderbolt firmware be updated in win through fwupdatetool？

### ISSUE THREAD

**Issue by Hush-vv** [SchmockLord/Hackintosh-Intel-i9-10900k-AsRock-Z490-Phantom-ITX-TB3#43]
[FwUpdateTool(v1.0.4).zip](https://github.com/SchmockLord/Hackintosh-Intel-i9-10900k-AsRock-Z490-Phantom-ITX-TB3/files/6033232/FwUpdateTool.v1.0.4.zip)
Can thunderbolt firmware be updated in win through fwupdatetool？

**Comment by klougithub** [comment]
the only reference to this procedure I've found is here
https://www.tonymacx86.com/threads/success-asrock-z390-phantom-gaming-itx-tb3-igpu-mojave-sff-build.277418/post-2090128
Someone with a Z490 tb3 should try it

**Comment by Hush-vv** [comment]
The ASRock Z390 phantom gaming itx / Tb3 I used before is to update thunderbolt firmware through FWupdatetool

**Comment by Hush-vv** [comment]
![IMG_4254](https://user-images.githubusercontent.com/61744850/109454762-e7a20880-7a8f-11eb-9014-249f1174938c.JPG)
After a try, it shows that the firmware has been updated successfully, but the thunderbolt has not been loaded successfully in the Mac

**Comment by klougithub** [comment]
Does it work in Windows?
Did you follow the 4th step after the flashing?

**Comment by Hush-vv** [comment]
I successfully updated the firmware through USB programmer and loaded the device tree of thunderbolt
<img width="733" alt="IMG_0006" src="https://user-images.githubusercontent.com/61744850/110214922-dfa7f580-7ee1-11eb-9f34-b88476a51d0f.png">

**Comment by klougithub** [comment]
so the FwUpdateTool doesn't work? Only with USB Flash programmer works?

**Comment by Hush-vv** [comment]
Yes, only through USB flash programmer
