### ISSUE TITLE
Onboard intel bluetooth and wifi

### ISSUE THREAD

**Issue by phi-alek** [SchmockLord/Hackintosh-Intel-i9-10900k-AsRock-Z490-Phantom-ITX-TB3#5]
My asrock itx tb3 mainboard is arriving the next couple of days. I use the built un wifi and.bluetooth on my nuc and it works nicely. Can i use the kext i have, inject them in your bootloader and have it working or do i need to.change something in the dsdt settings to open ports for the onboard intel wifi and Bluetooth? Thank you.

**Comment by SchmockLord** [comment]
Yeah, you need to create your own USB port configuration so the USB port is enabled for the internal Intel Bluetooth. Apart from that, you shouldn't need to change something.

**Comment by phi-alek** [comment]
Hi and thank you so much for that efi folder. My system runs with it now. Bluetooth and wufi worked right out of the box without changing anything. Ive just injected the kext. Actually the Bluetooth and wifi are very stable and reliable. 

But i have another issue. I can't login automatically. If i disable autamtic user login, i have a black screen when mas os catalina boots up. I need to write my password to enable the graphics. Then i can login and have enter my password again.
With enabled automatic login, i also need to enter my password after boot up or when i want to exit the screensafer, which is very odd.

**Comment by fidalgodev** [comment]
> Yeah, you need to create your own USB port configuration so the USB port is enabled for the internal Intel Bluetooth. Apart from that, you shouldn't need to change something.

doesn't your config have the USB port for the internal wifi/bluetooth card receive power? I thought it was enabled since you said you used the default wifi slot and just replaced the card.
I have a BCM94360CD plugged into the default wifi slot of the board, and it has power (with your config)

**Comment by phi-alek** [comment]
> > Yeah, you need to create your own USB port configuration so the USB port is enabled for the internal Intel Bluetooth. Apart from that, you shouldn't need to change something.
> 
> doesn't your config have the USB port for the internal wifi/bluetooth card receive power? I thought it was enabled since you said you used the default wifi slot and just replaced the card.
> I have a BCM94360CD plugged into the default wifi slot of the board, and it has power (with your config)

Like i have said, i didn't need to open any usb ports. I have only injected the Bluetooth and wifi kexts and it works very well.
