### ISSUE TITLE
Fan and other sensors

### ISSUE THREAD

**Issue by rajeevhans** [SchmockLord/Hackintosh-Intel-i9-10900k-AsRock-Z490-Phantom-ITX-TB3#8]
I have near identical hardware and I noticed Fan and CPU/GPU temp sensors aren't showing up. Anyone else had this issue?

**Comment by astralrick** [comment]
I have near identical hardware as well. I have the cpu temp but no gpu temp/fan. I use "macs fan control" cannot see the cpu fan but it works from the background (motherboards)

**Comment by rajeevhans** [comment]
Anyone else solve this issue with Fan sensors?

**Comment by SchmockLord** [comment]
Fixed with newest iStat
