### ISSUE TITLE
Artic Freezer 240 II on ASrock Z490I Motherboard

### ISSUE THREAD

**Issue by fidalgodev** [SchmockLord/Hackintosh-Intel-i9-10900k-AsRock-Z490-Phantom-ITX-TB3#9]
Not really related to the hackintosh.

I saw you have this cooler, and i just got one. But the pump doesn't seem to fit on the socket? It hits the VRM coolers. How did you managed to fit it?

**Comment by fidalgodev** [comment]
Nevermind, I had to switch the pump around (VRM fan pointing down), remove top VRM heatsink, install the pump and then put the top vrm back on!

**Comment by SchmockLord** [comment]
Yeah I did the same.
